### ISSUE TITLE
Use flatpickr for selecting a date to pair

### ISSUE THREAD

**Issue by dpaola2** [agency-of-learning/PairApp#1]
As a user, when I create a new pair request and select a date and time, I see a date picker instead of the browser default dropdown.

https://flatpickr.js.org/getting-started/

Investigate whether it's possible to keep the date and time as a single column in the DB or if we need to somehow split them up.

**Comment by afogel** [comment]
I'd like to take this on, please.

**Comment by dpaola2** [comment]
Go for it. I think there was a discussion about the best way to proceed - considering the fact that the date field is actually a date time field, there is an open question of how best to separate them.

**Comment by toyhammered** [comment]
This is is blocked due to https://github.com/agency-of-learning/PairApp/issues/14 (redesigning what a "Pair Request" is). This is still valid to be done afterwards though.

**Comment by afogel** [comment]
I think this is probably ready to pick up again, no?
