### ISSUE TITLE
[Standup Epic] Standup Meeting Group#index

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#117]
As a non-admin, I should be able to see all the standup meeting groups, organized by those I've joined and those I haven't.

I should be able to join a group I'm not a part of or leave one that I am a part of.

[Wireframes for the page](https://balsamiq.cloud/se3m7v2/puupn9o/r6A82)

**Comment by GALTdea** [comment]
I'll take on this one.

**Comment by afogel** [comment]
> I'll take on this one.

I think @toyhammered is already working on it;
