### ISSUE TITLE
[Standup Epic] Standup Meeting Group#show

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#118]
As a member of a standup meeting group, I should see all the standup meetings for the group, whether I've checked in, as well as have a CTA to check-in.

[Wireframes for this page](https://balsamiq.cloud/se3m7v2/puupn9o/r561A)

Edge case to consider: What should be displayed in the event that there are standup meetings for other members of the group that exist for a particular date, but no standup meeting for the individual viewing the Standup Meeting Group#show page?

**Comment by GALTdea** [comment]
I'd  like to work on this one!

**Comment by afogel** [comment]
@GALTdea - it seems like you're finishing up `StandupMeetingGroup#index`, right? If so, I'll take this.
