### ISSUE TITLE
Replace user email with users' names in views

### ISSUE THREAD

**Issue by JoshDevHub** [agency-of-learning/PairApp#142]
## Story
Currently, users are identified by their email addresses throughout the app. Examples can be seen when viewing pair requests or feedback:
![Selection_203](https://github.com/agency-of-learning/PairApp/assets/88392688/14a4389e-bff1-42a2-88ef-fd39a5b97ced)

With the completion of #115 , users would like to see others identified by name rather than email. The wireframes do a good job of showing how this should look: https://balsamiq.cloud/se3m7v2/puupn9o/r7BA4

## A PR Should
Make changes to to view templates and ViewComponents so that the user name is displayed on the following pages instead of their email:
- [x] pair request index
  - [x] Be sure to include the invitee select field for the new pair request form on the index page. Its options should display users by their names rather than email
- [x] pair request show
- [x] feedback index
- [x] feedback show

**Comment by jonichi16** [comment]
Hi, can I work on this? Thanks
