### ISSUE TITLE
[Standup Epic] Cron job to create new standup instances for members of standup meetng groups

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#152]

**Comment by toyhammered** [comment]
I'm wondering if we want to put this together with integrating with notifier gem. That is the real value in having these go out as cron jobs.

**Comment by afogel** [comment]
Now that we have the ability to create a new standup meeting, even on days when we don't have existing instances, I'd agree. That said, it could be an easy first issue for someone unfamiliar with writing cron tasks to try out, and could be augmented with the new functionality that is brought in by the notifier gem once we integrate it. I don't feel too strongly about this either way, but I figured making an issue was worthwhile so that it wouldn't fall off the radar.
What do you think?

**Comment by toyhammered** [comment]
I think if we implement the notifier gem ourselves as a separate task and include an example (for like Pair Request) then yeah this could be good. There are some nuances for when these should be created but could help them along with it.

**Comment by toyhammered** [comment]
Now that the notification gem is implemented, I'll quickly knock this out.
