### ISSUE TITLE
Linter for JS

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#168]
**Is your feature request related to a problem? Please describe.**
I see inconsistencies in linting/style in JS. So far, it's not being addressed, but I think it provides consistency for the entire team.

**Describe the solution you'd like**
Add a linter. [Eslint](https://eslint.org/) has fairly broad adoption, so might be a good option.

**Describe alternatives you've considered**
A cursory [look at some other options](https://blog.logrocket.com/modern-faster-alternatives-eslint/) suggests that there are alternatives. Rome looked most interesting to me, but we'll see.

**Comment by toyhammered** [comment]
Eslint is fine by me
