### ISSUE TITLE
Introduce "role" to a User

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#17]
Allow for a user to have a role. For now the 2 roles we need are
1. member (if you have a better name than this I am all ears)
2. admin
This should be an enum.

I don't think we need to go with something like https://github.com/RolifyCommunity/rolify which is just overkill.

**Comment by dvsconcept1986** [comment]
Would like to work on this.

**Comment by toyhammered** [comment]
sounds good, not sure how to assign you but will do so when I figure out.
