### ISSUE TITLE
[Profiles] Profiles#Show page

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#180]
1. Space for resume upload/show (functionality can be added in #179 )
2. Profile picture
3. short bio or description
  i. Add a new column to the user table that includes this. We can consider a new table that stores more of this info separately purely so the user table doesn’t become over bloated. Figuring out where that fine line is, is something that will need to be explored (and what fields we want where).
This could be in something potentially called a “profile”.

**Comment by JoshDevHub** [comment]
Going to get started on this one!
