### ISSUE TITLE
Pair request feedback

### ISSUE THREAD

**Issue by dpaola2** [agency-of-learning/PairApp#2]
As a pair request author and acceptor, when I visit PairApp after a pairing session concludes, I see a sticky reminder below the navbar that reminds me to fill out a feedback form on that particular session.

As a pair request author and acceptor, when I click to see a specific pair request, I can see the ratings and feedback from that session.

As a lurker / random user, I can only see who authored and accepted the pair request, I cannot see the ratings or the feedback.

# Implementation thoughts

Add these columns to the pair request model:

- author_overall_rating (“how do you think that session went?”) - 1 to 4 - self_rating (int, 1 to 4) - “How did you do?”
- acceptor_overall_rating (“how do you think that session went?”) - 1 to 4 - self_rating (int, 1 to 4) - “How did you do?”
- author_partner_rating (int, 1 to 4) - “How did they do?”
- acceptor_partner_rating (int, 1 to 4) - “How did they do?”
- author feedback for your partner (action text)
- acceptor feedback for your partner (action text)

Maybe use this for the ratings? https://shoelace.style/components/rating

**Comment by GALTdea** [comment]
I'd like to help with this! do we need to create an auth0  account to get our own secret credentials? I looked for test credentials in their docs and couldn't find one.

**Comment by dpaola2** [comment]
For posterity: you just need the `.env` file that I have on my machine. ask me for it in discord and I'll share :)

**Comment by GALTdea** [comment]
Hey Dave, Nathan and I would like to give this one a try

**Comment by dpaola2** [comment]
go for it!

**Comment by toyhammered** [comment]
@GALTdea and @ThomasNathan unsure if you have started this but I would **highly** recommend doing a design doc. The solution proposed here I don't entirely agree with (but don't want to take away from the process by just telling you what I think).

**Comment by GALTdea** [comment]
Hey Daniel, Yes, Nathan and I are working on it. This is definitely a good case for the design doc. There are so many design decisions that need to be made. I'll Talk to Nathan about it today.

**Comment by GALTdea** [comment]
Great, I talked to Nathan and we'll work on it tomorrow. Thank you!

**Comment by toyhammered** [comment]
will be creating a new issue for this.
