### ISSUE TITLE
[UserMenteeApplication] Backfill all applicants who previously applied

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#260]
We will be provided with some sort of csv from Dave which should include all past applicants and what the status of their application is (accepted/rejected). The backfill should:
1. create an account with some `SecureRandom.uuid` passoword (user can reset if they do decide to join)
2. fill out the UserMenteeApplication
3. Be given the appropriate status

This will most likely need to be done via ssh in Heroku. You can locally convert the csv to json, copy paste it into console and setup some job to ingest them.

**Comment by toyhammered** [comment]
@dpaola2 would you be able to supply us with a csv?

**Comment by dpaola2** [comment]
@toyhammered will send in discord since it has private people data

**Comment by afogel** [comment]
This is now completed. For audit purposes, #282 contains the code used to backfill.
