### ISSUE TITLE
[UserMenteeApplication] Allow users to reapply if they were previously rejected

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#272]
If a user was previously rejected, allow them to reapply (if there is a new UserMenteeApplicationCohorts available that they are not part of). The way this would work is that it would take all the existing information and shove it into the form. They will be able to review/edit the form and then click submit (which will reapply them).

This is just a shortcut to allow them to easily reuse their information. They could in theory, just apply again and put in any information.

**Comment by toyhammered** [comment]
Blocked until https://github.com/agency-of-learning/PairApp/issues/271 is finished

**Comment by afogel** [comment]
@JoshDevHub -- presumably you've run across this, but while completed #260 , I noticed that the association on the User model is `has_one :mentee_application, class_name: 'UserMenteeApplication', dependent: :destroy` but I think we really actually want it to be `has_many :mentee_applications, class_name: 'UserMenteeApplication', dependent: :destroy`.

Anyway, figured I'd flag it just in case it had been under the radar

**Comment by toyhammered** [comment]
great callout! Totally missed this when we added the cohorts.
