### ISSUE TITLE
Update readme to simplify even further

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#276]
example being: tell people to `brew install redis` not just assume they have it.

**Comment by afogel** [comment]
see https://github.com/agency-of-learning/PairApp/wiki/Step%E2%80%90by%E2%80%90step-instructions-to-install-the-dependencies-of-our-application

**Comment by afogel** [comment]
@toyhammered I think this is done? I'll let you close once you review the wiki
