### ISSUE TITLE
[UserMenteeApplicationNotes] Build a rubric table for decision-making and notes

### ISSUE THREAD

**Issue by GALTdea** [agency-of-learning/PairApp#295]
When updating  Mentee application statuses, admins/reviewers are encouraged to write notes explaining the reasoning for their decision. We need to add a rubric table with checkboxes for common criteria. 
Doing this will allow us to standardize the decision-making process and consistency, making the application review faster and more effective. 

Add a set of checkboxes to the manage_application form that includes some of the most common decision-making criteria, e.g, 
note: the goal of this issue to write functionality and not all the options needed. 

- [ ] Does not have required skills
- [ ] Cannot commit to the required time
- [ ] Goals not aligned with the program's objectives
- [ ] Poor communication during the review process
- [ ] other...

**Additional context**

**Comment by toyhammered** [comment]
Please move this to a feature pitch.
