### ISSUE TITLE
[UserMenteeApplication] LinkedIn + Github Validations missing

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#314]
We should validate that the urls provided are correct. We can either:
1. just ask for a username and shove the url prior to saving
2. expect them to include url
3. just store the username and automatically apply url via model method (we won't save the url directly).

**Comment by elhalvers** [comment]
Looks like this one is closed

**Comment by GALTdea** [comment]
@elhalvers Are you tackling this one?

**Comment by elhalvers** [comment]
Sure! It looks like there is code in the 'Profile' model that is supposed to validate, but it does not seem to be actually validating.

**Comment by GALTdea** [comment]
oh yeah, Profile mode is a different model. what we're looking to validate is the UserMenteeApplication model links

**Comment by elhalvers** [comment]
Thank you @GALTdea! I had that first and was seduced by the 'Profile' model! 😂

**Comment by GALTdea** [comment]
haha, totally confusing.. but i'm glad you found those because you can totally use the same validations. you just have to change the attribute names

**Comment by GALTdea** [comment]
as an example, the linked_in attr in profile "linked_in_link" should be linkedin_url in the UserMenteeApplication
