### ISSUE TITLE
Send email to all previously reject applicants that were imported in

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#322]
We should grab all the users who were imported into the `Original` cohort and send an email to them once we open up a new cohort. Unsure what this email should say.

**Comment by afogel** [comment]
Proposed copy:

Subject: Invitation to apply to the Agency of Learning

Dear ${full_name},

Thank you for previously expressing interest to join us at the Agency of Learning. 

We are currently opening up a new cohort of early-career developers living and working in the US to join us. Given your previous interest, we wanted to invite you to reapply to the Agency of Learning.

To reapply, please :
1. ...
2. ...
3. ...

**Comment by afogel** [comment]
ping @toyhammered on updated copy?

**Comment by toyhammered** [comment]
Talking with Dave about this.

Make sure to include in the email that we have their old application still that will help them fill out the new one.

**Comment by toyhammered** [comment]
@afogel the copy you have looks great. We just need to add something along the lines of what I commented above. 

Also once this rake task is finished we won't be running it right away (not until we are ready to open the gates)

**Comment by afogel** [comment]
@toyhammered @dpaola2
The updated copy reads as follows. Let me know if you'd like me to make any modifications.

> Thank you for previously expressing interest to join us at the Agency of Learning.
>
> We are currently opening up a new cohort to early-career developers with some experience using Ruby on Rails to join us. In particular, we are looking for applicants residing in North America who can devote at least 10 hours per week to the Agency.
>
> Given your previous interest, we wanted to invite you to **reapply to the Agency of Learning**. To speed things up, we've filled in your reapplication form with information from your previous application.
>
> To reapply, please follow these steps: 
> ... (same as before)

**Comment by dpaola2** [comment]
Looks great to me!
