### ISSUE TITLE
[UserMenteeApplication] Make working social media links

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#332]
![Image](https://user-images.githubusercontent.com/1283983/269138449-76ac9394-87ba-4a4d-8d72-14dac26bd127.png)

Both these links should be clickable. We don't need to add the icons cause i'd prefer to see the url. They should also open up in a new tab.

**Comment by chahmedejaz** [comment]
Hey @toyhammered - I've submitted the PR for this issue. Would love to hear your thoughts on it. Thanks :)
