### ISSUE TITLE
[UserMenteeApplication] Empty State for Past Applications

### ISSUE THREAD

**Issue by JoshDevHub** [agency-of-learning/PairApp#340]
After signing up to become a member, applicants will see this page:

![Image](https://github.com/agency-of-learning/PairApp/assets/88392688/5a73e17d-5d75-4cb8-aa7e-2867a408e063)

Because the 'Past Applications' section is empty, having that heading present feels off. If users don't have any past applications, this heading should not show on the page.

**Comment by afogel** [comment]
Great callout!

**Comment by chahmedejaz** [comment]
Hey @afogel - I'd love to fix this, can you please assign it to me? Thanks. :)

**Comment by chahmedejaz** [comment]
Hey @afogel, @JoshDevHub - I've submitted the small fix for this. I'd love to hear your thoughts on this. Thanks :)

**Comment by chahmedejaz** [comment]
Hey @afogel - Just a wanted to know if there is something missing for latest changes? :sweat_smile:
