### ISSUE TITLE
[UserMenteeApplication] Empty state for social media links

### ISSUE THREAD

**Issue by chahmedejaz** [agency-of-learning/PairApp#371]
**Bug Description**
On the user application view page (`/user_mentee_applications/:id`), if he has no social media link, then we should not be showing the heading for that social media e.g
![image](https://github.com/agency-of-learning/PairApp/assets/59338032/8f77f224-ee5c-469a-8759-66122310a227)

**Comment by afogel** [comment]
In this case, I think keeping it in is fine. Seeing no social media links is actually important signal for us, too.

**Comment by chahmedejaz** [comment]
Oh right, great then :+1:
