### ISSUE TITLE
[UserMenteeApplication] Validate presence of protocol for application URLs

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#378]
![Image](https://github.com/agency-of-learning/PairApp/assets/1283983/848c5630-4715-437c-a3df-dc0a4efcf086)

Doesn't lead to linkedIn but to our pairapp (with a 500 error).

**Comment by afogel** [comment]
^ this seems like a validation error (or a formatting error). No `https://` before linkedin. Linkedin URL does work for those that do include it.
