### ISSUE TITLE
[UserMenteeApplication] on Show page, admin should have back button the list of applications for cohort

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#381]
![Image](https://github.com/agency-of-learning/PairApp/assets/1283983/c8bcd2e0-9ed2-42d3-a7fe-46ebad2296ac)

On the show page somewhere at the top can we have a back button that takes us back to the cohort index page?

**Comment by GALTdea** [comment]
I'll tackle this @toyhammered ! 😃

**Comment by JoshDevHub** [comment]
Closed by #386
