### ISSUE TITLE
[UserMenteeApplication] The show page (when clicking in) should include som user details

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#385]
When you are on a persons application page, we should include some basic details like first and last name, maybe email also. Right now it shows nothing and is kind of confusing.

**Comment by JoshDevHub** [comment]
It makes sense to have this for application reviewers. Do you want these details to show the applicant as well @toyhammered ?

**Comment by toyhammered** [comment]
> It makes sense to have this for application reviewers. Do you want these details to show for the applicant as well @toyhammered ?

Thinking about this more I'd like to more properly handle this in v2. For this initial version though, it can be an admin only thing on the same page.
