### ISSUE TITLE
[StandupMeeting] Add job for marking older draft meetings as missed

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#391]
Seems like the job that expires drafts after 1 week isn't working properly?

**Comment by JoshDevHub** [comment]
Do you mean that the Pair Request auto-expire job isn't working? I couldn't find an existing job for expiring Standup Meetings

**Comment by toyhammered** [comment]
> Do you mean that the Pair Request auto-expire job isn't working? I couldn't find an existing job for expiring Standup Meetings

oh god.. I might be crazy and mixing up the Standup Meetings with Pair Requests lol. I guess it just never got done because we do have a `missed` status.

**Comment by JoshDevHub** [comment]
I guess we could change this ticket to be about introducing a job that does this then? If a standup meeting is a 1 week+ old and hasn't been filled in, the background worker should change the meeting's status to `missed`. Does that sound good @toyhammered ?

**Comment by toyhammered** [comment]
> I guess we could change this ticket to be about introducing a job that does this then? If a standup meeting is a 1 week+ old and hasn't been filled in, a background worker should change the meeting's status to `missed`. Does that sound good @toyhammered ?

yup this is perfect.
