### ISSUE TITLE
Heroku app

### ISSUE THREAD

**Issue by dpaola2** [agency-of-learning/PairApp#4]
Get the app running on a heroku instance so that we can use it. Once it's up and running I can add the correct URLs to auth0 for user login.

**Comment by toyhammered** [comment]
Random food for though, maybe we can try to new hip hosting https://fly.io/. (I am really not a fan of heroku anymore)

**Comment by dpaola2** [comment]
Let's stick with Heroku for now. I don't want to introduce complexity and unfamiliarity at a time when the project is just getting off the ground. The goal is to ship fast, ship real value, and ship ship ship. Not to try out the latest and greatest.
