### ISSUE TITLE
Add cancelled state to PairRequest

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#53]
Right now when the user creates a PairRequest (they are the author) they only have the ability to "reject" it afterwards. We should add another state called "cancelled" that is specific to the author.
Author can cancel a PairRequest
Invitee can reject a PairRequest. Invitee can also accept, then reject.

Make sure to update the view to show this change.

**Comment by dvsconcept1986** [comment]
I would like to take crack at this issue.

**Comment by toyhammered** [comment]
@dvsconcept1986 any status update on this?

**Comment by afogel** [comment]
I'll take this. I'll turn to it after I finish hotwiring #86 later today/tomorrow
