### ISSUE TITLE
Logout bug

### ISSUE THREAD

**Issue by GALTdea** [agency-of-learning/PairApp#7]
When in the pair_requests view if user clicks on logout link a routing error occurs: 
When logging out from , a routing error occurs. 

when at the root view, if user clicks logout link the below error occurs:
dev-w32ag8yvc11fbtpi
Oops!, something went wrong
There could be a misconfiguration in the system or a service outage. We track these errors automatically, but if the problem persists feel free to contact us.
Please try again.

**Comment by toyhammered** [comment]
Going to close this out because Devise has been implemented and should be working properly.
