### ISSUE TITLE
Bug: Redirect unauthenticated users to login page

### ISSUE THREAD

**Issue by JoshDevHub** [agency-of-learning/PairApp#73]
Currently, users aren't redirected to login page if they visit a protected URL without being logged in.

## To recreate:
1. Run the local dev server
2. Be sure to logout if you're logged in
3. Visit `localhost:3000/pair_requests` and you should see the error

## A fix should:
- Redirect any unauthenticated user to the login page if they visit some protected URL (ie one that requires a logged in user). Devise provides a helper called `authenticate_user!` that you can run in a controller filter to implement this.
- While working on this, another change I think would be good is to root unauthenticated users to the login page. So if you visit `localhost:3000/` while not logged in, you should see the login page and not have to click any links/buttons to get there.

Glad to answer any questions!

**Comment by RocDavenport** [comment]
I am interested in this issues.

**Comment by JoshDevHub** [comment]
Apologies on shifting requirements but after looking at some of phase2 for MVP, it looks like parts of the app will eventually be available to public, unauthenticated users -- and we probably don't want to root such users to the login page since they won't have an account.

This just means that we can skip my second bullet point in the issue and just stick to redirecting users off of protected routes if they're not signed in.

Sorry for the change @RocDavenport

**Comment by elhalvers** [comment]
Hey @RocDavenport Let me know if you would like to pair on this issue.

Thanks!

: )
