### ISSUE TITLE
Add user first_name and last_name property to User

### ISSUE THREAD

**Issue by GALTdea** [agency-of-learning/PairApp#81]
The User model currently lacks a `first_name` and `last_name` property, which limits the amount of information that can be stored and displayed for each user. 

Due to the small table we have, this can be done entirely via 1 migration (single PR). When you create the design doc for this, please do talk about the different tradeoffs of doing this directly via a migration and any other ways this could be handled (if for instance we had a bigger table).

**Comment by RocDavenport** [comment]
I would be interested in taking on this issue.
