### ISSUE TITLE
Change Pundit scope for "admin" users.

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#83]
Right now our Pundit Scopes will check if the user is an admin. If they are, it will display all the records (for an index, PairRequest Feedback, etc..). Thinking through, this is not the desired behavior. All scopes should be scoped to the user.

Later on, we will actually create an admin view which will handle displaying these all. Right now admin/member view is kind of muddled which is bad.

**Comment by elhalvers** [comment]
I would be happy to work on this! : )
