### ISSUE TITLE
Show partner's time zone to make clear what time is being set

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#91]
As a user, when I create a new Pair Request, I'm asked to select a time/date. However, it's not clear whether I'm selecting a time/date based on my timezone, or my partner's timezone.

**Proposal:**
After I select my partner, whenever I select a date/time, it should be for my local time. Next to the date/time field, when I select a time, it should display what the selected time is in my partner's timezone.

**Comment by ShamiTomita** [comment]
I would love to work on this! Thank you @afogel !
