### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by toyhammered** [agency-of-learning/PairApp#98]
Create a simple FAQ Page that will give some helpful tips to the people about this app, purpose, and common questions they might have. Some starters can be:
1. What is the purpose of this app?
2. Who would benefit from this app?
3. How do I contribute to this app?

This page does not need to be supported by a model. All these questions/answers can be hardcoded in the front-end (or as a const in the controller). For the design doc, the only thing that it needs to include is a place where we can disucss which questions to add.

The wireframes for this one are important just so we can make this feel right. (This can be done on balsamiq, if you need an invite let @toyhammered know)

**Comment by afogel** [comment]
Curious whether this is a good enough starting point for creating the format of the FAQ: https://tailwindui.com/components/marketing/sections/faq-sections#component-8699d80b13ef524eb573e54b4d4b89d1

**Comment by toyhammered** [comment]
> Curious whether this is a good enough starting point for creating the format of the FAQ: https://tailwindui.com/components/marketing/sections/faq-sections#component-8699d80b13ef524eb573e54b4d4b89d1

yeah that is perfect!

**Comment by toyhammered** [comment]
> Questions:
> 
> 1. What is the purpose of this app?
>    This tool helps junior developers who want to join the industry by creating a central place to organize programming practices in professional team settings.
>    To date, we support:
> 
> * scheduling pair requests and providing feedback after pairing
> * participating in async standups for team projects
> 
> 2. Who would benefit from this app?
>    Currently, members of the Agency of Learning benefit from this app, as we use it internally to manage our team projects.
>    However, as we develop more features, we expect to open access to other organizations who interested in managing team practices while emphasizing mentorship for early-career developers.
> 3. How do I contribute to this app?
>    We have open issues created on our [Github Repo](https://github.com/agency-of-learning/PairApp/issues). We generally prefer people who are part of the Agency of Learning to pick those up because we would like for you to work in pairs with other developers. You can submit an application to the Agency of Learning [here](https://agencyoflearning.com/).
> 4. Can I show contributions I have done to future employers?
>    Of course! This was the main purpose for creating this app. We want you to be able to showcase your skills and show code that is being used on a real app that other people are using.
> 5. What is a Design Doc and where can I view what others have written.
>    You can view a sample design doc that goes through the steps needed to create one [here](https://www.notion.so/0fa06a5726c248c5b75e1c82bf094542?pvs=21). You can view the design docs that are currently in progress and completed [here](https://www.notion.so/Design-Docs-1db123d6f8d64cea9d4998cb1ad90c92?pvs=21).

thank you for extracting!
